// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Kogut struct {
	ID   int32       `json:"id"`
	Name string      `json:"name"`
	Age  pgtype.Int4 `json:"age"`
	Sex  bool        `json:"sex"`
}
