// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateKogut(ctx context.Context, arg CreateKogutParams) (Kogut, error)
	DeleteKogut(ctx context.Context, id int32) error
	GetAllKoguts(ctx context.Context) ([]Kogut, error)
	GetKogut(ctx context.Context, id int32) (Kogut, error)
	UpdateKogut(ctx context.Context, arg UpdateKogutParams) (Kogut, error)
}

var _ Querier = (*Queries)(nil)
